version: '3.8'
services:
  db:
    image: mysql:8.0.35
    container_name: weight_chart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: weight_chart
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: weight_chart_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/weight_chart
      PORT: 5000
    ports:
      - "5000:5000"
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"
    volumes:
      - .:/app

volumes:
  db_data:
